name: Build

on: [ push, workflow_dispatch ]

jobs:
  cmake-on-linux:

    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        build_type: [ Release ]

    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo apt install libtbb-dev

      - name: Configure and build
        run: |
          cmake . -B build -DECOS_BUILD_EXAMPLES=ON -DECOS_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build

      - name: Test
        run: |
          cd build/tests
          ctest --no-tests=error --output-on-failure

      - uses: actions/upload-artifact@v4
        if: matrix.build_type == 'Release'
        with:
          name: ecos-${{ matrix.os }}
          path: |
            build/bin/ecos*
            build/bin/proxyfmu*
            build/bin/libecosc.*

  cmake-on-windows:

    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022 ]
        build_type: [ Release ]

    steps:
      - uses: actions/checkout@v4

      - name: Configure and build
        run: |
          cmake . -A x64 -B build -DECOS_BUILD_EXAMPLES=ON -DECOS_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: |
          cd build/tests
          ctest -C ${{ matrix.build_type }} --no-tests=error --output-on-failure

      - uses: actions/upload-artifact@v4
        if: matrix.build_type == 'Release'
        with:
          name: ecos-${{ matrix.os }}
          path: |
            build/bin/ecos*
            build/bin/proxyfmu*
            build/bin/libecosc.*

  python-linux-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: cmake-on-linux  # only run after cmake-on-linux succeeds

    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo apt install libtbb-dev

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download ecospy binaries
        uses: actions/download-artifact@v4
        with:
          name: ecos-ubuntu-22.04
          path: ecospy/binaries

      - name: Make proxyfmu executable
        run: chmod +x ecospy/binaries/proxyfmu

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Run Python tests
        run: |
          pytest ecospy/tests -v

  python-windows-tests:
    runs-on: windows-2022
    timeout-minutes: 10
    needs: cmake-on-windows  # only run after cmake-on-windows succeeds

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download ecospy binaries
        uses: actions/download-artifact@v4
        with:
          name: ecos-windows-2022
          path: ecospy/binaries

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest

      - name: Run Python tests
        run: |
          pytest ecospy/tests -v
